[workspace]
members = [
    "ocl",
    "ocl/ocl-extras",
    "ocl/examples/images",
    "ocl/examples/images_safe_clamp",
	"ocl/examples/opencl_2_1",
	"ocl/examples/proto",
	"ocl-core",
	"ocl-core/ocl-core-vector",
	"cl-sys",
  "ocl-interop",
]
