	system u0 (
		.clk_50_clk                          (<connected-to-clk_50_clk>),                          //            clk_50.clk
		.reset_50_reset_n                    (<connected-to-reset_50_reset_n>),                    //          reset_50.reset_n
		.kernel_clk_clk                      (<connected-to-kernel_clk_clk>),                      //        kernel_clk.clk
		.fpga_memory_mem_a                   (<connected-to-fpga_memory_mem_a>),                   //       fpga_memory.mem_a
		.fpga_memory_mem_ba                  (<connected-to-fpga_memory_mem_ba>),                  //                  .mem_ba
		.fpga_memory_mem_ck                  (<connected-to-fpga_memory_mem_ck>),                  //                  .mem_ck
		.fpga_memory_mem_ck_n                (<connected-to-fpga_memory_mem_ck_n>),                //                  .mem_ck_n
		.fpga_memory_mem_cke                 (<connected-to-fpga_memory_mem_cke>),                 //                  .mem_cke
		.fpga_memory_mem_cs_n                (<connected-to-fpga_memory_mem_cs_n>),                //                  .mem_cs_n
		.fpga_memory_mem_dm                  (<connected-to-fpga_memory_mem_dm>),                  //                  .mem_dm
		.fpga_memory_mem_ras_n               (<connected-to-fpga_memory_mem_ras_n>),               //                  .mem_ras_n
		.fpga_memory_mem_cas_n               (<connected-to-fpga_memory_mem_cas_n>),               //                  .mem_cas_n
		.fpga_memory_mem_we_n                (<connected-to-fpga_memory_mem_we_n>),                //                  .mem_we_n
		.fpga_memory_mem_reset_n             (<connected-to-fpga_memory_mem_reset_n>),             //                  .mem_reset_n
		.fpga_memory_mem_dq                  (<connected-to-fpga_memory_mem_dq>),                  //                  .mem_dq
		.fpga_memory_mem_dqs                 (<connected-to-fpga_memory_mem_dqs>),                 //                  .mem_dqs
		.fpga_memory_mem_dqs_n               (<connected-to-fpga_memory_mem_dqs_n>),               //                  .mem_dqs_n
		.fpga_memory_mem_odt                 (<connected-to-fpga_memory_mem_odt>),                 //                  .mem_odt
		.fpga_memory_oct_rzqin               (<connected-to-fpga_memory_oct_rzqin>),               //   fpga_memory_oct.rzqin
		.fpga_sdram_status_local_init_done   (<connected-to-fpga_sdram_status_local_init_done>),   // fpga_sdram_status.local_init_done
		.fpga_sdram_status_local_cal_success (<connected-to-fpga_sdram_status_local_cal_success>), //                  .local_cal_success
		.fpga_sdram_status_local_cal_fail    (<connected-to-fpga_sdram_status_local_cal_fail>),    //                  .local_cal_fail
		.memory_mem_a                        (<connected-to-memory_mem_a>),                        //            memory.mem_a
		.memory_mem_ba                       (<connected-to-memory_mem_ba>),                       //                  .mem_ba
		.memory_mem_ck                       (<connected-to-memory_mem_ck>),                       //                  .mem_ck
		.memory_mem_ck_n                     (<connected-to-memory_mem_ck_n>),                     //                  .mem_ck_n
		.memory_mem_cke                      (<connected-to-memory_mem_cke>),                      //                  .mem_cke
		.memory_mem_cs_n                     (<connected-to-memory_mem_cs_n>),                     //                  .mem_cs_n
		.memory_mem_ras_n                    (<connected-to-memory_mem_ras_n>),                    //                  .mem_ras_n
		.memory_mem_cas_n                    (<connected-to-memory_mem_cas_n>),                    //                  .mem_cas_n
		.memory_mem_we_n                     (<connected-to-memory_mem_we_n>),                     //                  .mem_we_n
		.memory_mem_reset_n                  (<connected-to-memory_mem_reset_n>),                  //                  .mem_reset_n
		.memory_mem_dq                       (<connected-to-memory_mem_dq>),                       //                  .mem_dq
		.memory_mem_dqs                      (<connected-to-memory_mem_dqs>),                      //                  .mem_dqs
		.memory_mem_dqs_n                    (<connected-to-memory_mem_dqs_n>),                    //                  .mem_dqs_n
		.memory_mem_odt                      (<connected-to-memory_mem_odt>),                      //                  .mem_odt
		.memory_mem_dm                       (<connected-to-memory_mem_dm>),                       //                  .mem_dm
		.memory_oct_rzqin                    (<connected-to-memory_oct_rzqin>),                    //                  .oct_rzqin
		.peripheral_hps_io_emac0_inst_TX_CLK (<connected-to-peripheral_hps_io_emac0_inst_TX_CLK>), //        peripheral.hps_io_emac0_inst_TX_CLK
		.peripheral_hps_io_emac0_inst_TXD0   (<connected-to-peripheral_hps_io_emac0_inst_TXD0>),   //                  .hps_io_emac0_inst_TXD0
		.peripheral_hps_io_emac0_inst_TXD1   (<connected-to-peripheral_hps_io_emac0_inst_TXD1>),   //                  .hps_io_emac0_inst_TXD1
		.peripheral_hps_io_emac0_inst_TXD2   (<connected-to-peripheral_hps_io_emac0_inst_TXD2>),   //                  .hps_io_emac0_inst_TXD2
		.peripheral_hps_io_emac0_inst_TXD3   (<connected-to-peripheral_hps_io_emac0_inst_TXD3>),   //                  .hps_io_emac0_inst_TXD3
		.peripheral_hps_io_emac0_inst_RXD0   (<connected-to-peripheral_hps_io_emac0_inst_RXD0>),   //                  .hps_io_emac0_inst_RXD0
		.peripheral_hps_io_emac0_inst_MDIO   (<connected-to-peripheral_hps_io_emac0_inst_MDIO>),   //                  .hps_io_emac0_inst_MDIO
		.peripheral_hps_io_emac0_inst_MDC    (<connected-to-peripheral_hps_io_emac0_inst_MDC>),    //                  .hps_io_emac0_inst_MDC
		.peripheral_hps_io_emac0_inst_RX_CTL (<connected-to-peripheral_hps_io_emac0_inst_RX_CTL>), //                  .hps_io_emac0_inst_RX_CTL
		.peripheral_hps_io_emac0_inst_TX_CTL (<connected-to-peripheral_hps_io_emac0_inst_TX_CTL>), //                  .hps_io_emac0_inst_TX_CTL
		.peripheral_hps_io_emac0_inst_RX_CLK (<connected-to-peripheral_hps_io_emac0_inst_RX_CLK>), //                  .hps_io_emac0_inst_RX_CLK
		.peripheral_hps_io_emac0_inst_RXD1   (<connected-to-peripheral_hps_io_emac0_inst_RXD1>),   //                  .hps_io_emac0_inst_RXD1
		.peripheral_hps_io_emac0_inst_RXD2   (<connected-to-peripheral_hps_io_emac0_inst_RXD2>),   //                  .hps_io_emac0_inst_RXD2
		.peripheral_hps_io_emac0_inst_RXD3   (<connected-to-peripheral_hps_io_emac0_inst_RXD3>),   //                  .hps_io_emac0_inst_RXD3
		.peripheral_hps_io_sdio_inst_CMD     (<connected-to-peripheral_hps_io_sdio_inst_CMD>),     //                  .hps_io_sdio_inst_CMD
		.peripheral_hps_io_sdio_inst_D0      (<connected-to-peripheral_hps_io_sdio_inst_D0>),      //                  .hps_io_sdio_inst_D0
		.peripheral_hps_io_sdio_inst_D1      (<connected-to-peripheral_hps_io_sdio_inst_D1>),      //                  .hps_io_sdio_inst_D1
		.peripheral_hps_io_sdio_inst_CLK     (<connected-to-peripheral_hps_io_sdio_inst_CLK>),     //                  .hps_io_sdio_inst_CLK
		.peripheral_hps_io_sdio_inst_D2      (<connected-to-peripheral_hps_io_sdio_inst_D2>),      //                  .hps_io_sdio_inst_D2
		.peripheral_hps_io_sdio_inst_D3      (<connected-to-peripheral_hps_io_sdio_inst_D3>),      //                  .hps_io_sdio_inst_D3
		.peripheral_hps_io_uart0_inst_RX     (<connected-to-peripheral_hps_io_uart0_inst_RX>),     //                  .hps_io_uart0_inst_RX
		.peripheral_hps_io_uart0_inst_TX     (<connected-to-peripheral_hps_io_uart0_inst_TX>),     //                  .hps_io_uart0_inst_TX
		.peripheral_hps_io_i2c0_inst_SDA     (<connected-to-peripheral_hps_io_i2c0_inst_SDA>),     //                  .hps_io_i2c0_inst_SDA
		.peripheral_hps_io_i2c0_inst_SCL     (<connected-to-peripheral_hps_io_i2c0_inst_SCL>),     //                  .hps_io_i2c0_inst_SCL
		.peripheral_hps_io_gpio_inst_GPIO41  (<connected-to-peripheral_hps_io_gpio_inst_GPIO41>),  //                  .hps_io_gpio_inst_GPIO41
		.peripheral_hps_io_gpio_inst_GPIO42  (<connected-to-peripheral_hps_io_gpio_inst_GPIO42>),  //                  .hps_io_gpio_inst_GPIO42
		.peripheral_hps_io_gpio_inst_GPIO43  (<connected-to-peripheral_hps_io_gpio_inst_GPIO43>),  //                  .hps_io_gpio_inst_GPIO43
		.peripheral_hps_io_gpio_inst_GPIO44  (<connected-to-peripheral_hps_io_gpio_inst_GPIO44>)   //                  .hps_io_gpio_inst_GPIO44
	);

